//@version=4
// PCC Sunday Trade Series
// BLOCK - Prince of Songkla University, Phuket, Thailand
// Author: Tanwa Arpornthip
// Contact: tanwa.a@phuket.psu.ac.th
// 2021-09-25

strategy("PCC main indicator template", overlay=true, default_qty_type=strategy.percent_of_equity, 
  default_qty_value=100, commission_type=strategy.commission.percent, commission_value=0, 
  pyramiding=0, calc_on_order_fills=false, precision=7, calc_on_every_tick=true)

// === STRATEGY PARAMETERS ===
// === With inputs
want_long = input(title="Long order?", type=input.bool, defval=true)
want_short = input(title="Short order?", type=input.bool, defval=true)
tp_atr = input(title="x ATR TP", type=input.float, defval=1.0, minval=0)
sl_atr = input(title="x ATR SL", type=input.float, defval=1.0, minval=0)
atr_range = input(title="ATR period", type=input.integer, defval=14)

direction = input(title="Direction", defval="Conventional", options=["Contrarian", "Conventional"])

// === Without inputs
average_true_range = atr(atr_range)

// === INPUT BACKTEST RANGE ===
FromYear = input(defval=2017, title="From Year", minval=2000)
ToYear = input(defval=9999, title="To Year", minval=2000)
FromMonth = input(defval=1, title="From Month", minval=1, maxval=12)
ToMonth = input(defval=1, title="To Month", minval=1, maxval=12)
FromDay = input(defval=1, title="From Day", minval=1, maxval=31)
ToDay = input(defval=31, title="To Day", minval=1, maxval=31)

// === Initializing some variables
stop_loss_level = float(na)
take_profit_level = float(na)
short_condition = false
long_condition = false


////////////////////////////////
// Ignore this part for now   //
//⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇⬇// 

long_confirm = true
short_confirm = true

long_volume = true
short_volume = true

//⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆⬆// 
// Ignore this part for now  //
///////////////////////////////

// === Define useful functions ===
start = timestamp(FromYear, FromMonth, FromDay, 00, 00)  // backtest start window
finish = timestamp(ToYear, ToMonth, ToDay, 23, 59)  // backtest finish window
window() =>  // create function "within window of time"
    time >= start and time <= finish ? true : false


// =======================================//
//       USER CHANGEABLE SECTION          // 
// =======================================//

// Define your main indicator here //
// SMA(25) is used as an example
ma_tf = input(title="MA timeframe", type=input.integer, defval=25, minval=1)
ma_value = sma(close,ma_tf)

// Define long condition and short condition
// Direction is defined by an input on the UI
if direction == "Conventional"
    // Conventional means using the indicator traditionally (i.e. the same way stock market does)
    // Define long condition and short condition
    short_condition := crossunder(close,ma_value) 
    long_condition := crossover(close,ma_value)
else
    // Non-conventional (contrarian) means doing things oppositely
    short_condition := crossover(close,ma_value)
    long_condition := crossunder(close,ma_value) 




// End of user changeable section
// ================================




// Order entering
strategy.entry("Long", strategy.long, when=long_condition and long_confirm and long_volume and want_long and window() and strategy.position_size == 0)
strategy.entry("Short", strategy.short, when=short_condition and short_confirm and short_volume and want_short and window() and strategy.position_size == 0)

// Risk management
bought = (long_condition[1] or short_condition[1]) and 
   abs(strategy.position_size[0]) > abs(strategy.position_size[1])
since_entry = barssince(bought)
if strategy.position_size != 0
    if strategy.position_size > 0
        //Going long. Do these
        stop_loss_level := strategy.position_avg_price - sl_atr * average_true_range[since_entry]
        take_profit_level := strategy.position_avg_price + tp_atr * average_true_range[since_entry]
        take_profit_level
    else
        //Going short. Do these
        stop_loss_level := strategy.position_avg_price + sl_atr * average_true_range[since_entry]
        take_profit_level := strategy.position_avg_price - tp_atr * average_true_range[since_entry]
        take_profit_level
else
    if strategy.position_size[1] != 0
        //Plot one more bar for the order closing bar
        stop_loss_level := stop_loss_level[1]
        take_profit_level := take_profit_level[1]
        take_profit_level
    else
        //With no order and not a closing bar. Plot nothing
        stop_loss_level := na
        take_profit_level := na
        take_profit_level

strategy.exit("LongClose", "Long", stop=stop_loss_level, limit=take_profit_level)
strategy.exit("ShortClose", "Short", stop=stop_loss_level, limit=take_profit_level)
strategy.close_all(when=time > finish)

plotchar(long_condition? 1:0, char="🟢")
plotchar(short_condition? 1:0, char="🔴")
plot(stop_loss_level, style=plot.style_linebr, color=color.red)
plot(take_profit_level, style=plot.style_linebr, color=color.green)
//plot(strategy.position_size)

